name: Build Xvfb (x86_64 + ARM64)

on:
  push:
    branches: [main]         # Runs when pushing to main
  workflow_dispatch:   # Manual trigger

jobs:
  build_x86:
    runs-on: ubuntu-latest
    container:
      image: debian:10

    steps:
      - name: Fix Debian 10 repositories
        run: |
          sed -i 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' /etc/apt/sources.list
          sed -i 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' /etc/apt/sources.list

          echo 'Acquire::Check-Valid-Until "false";' \
            > /etc/apt/apt.conf.d/99no-check-valid

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install base dependencies (host)
        run: |
          apt-get update
          apt-get install -y meson ninja-build pkg-config python3 python3-pip build-essential git x11-xkb-utils libjpeg-dev

      - name: Build project
        run: |
          bash .gitlab-ci/debian-install.sh
          meson setup build
          meson compile -C build

        continue-on-error: true

      - name: Show binary info
        run: |
          file build/hw/vfb/Xvfb || true
          file build/hw/xfree86/Xorg || true

      - name: Upload build artifact XVFB
        uses: actions/upload-artifact@v4
        if: success() || always()
        with:
          name: Xvfb_x86
          path: build/hw/vfb/Xvfb

      - name: Upload Xorg (if present)
        if: ${{ hashFiles('build/hw/xfree86/Xorg') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: Xorg-x86
          path: build/hw/xfree86/Xorg

  build_arm64:
    runs-on: [self-hosted, arm64_d11]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Meson build cache
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-meson-build-${{ hashFiles('**/meson.build') }}
          restore-keys: |
            ${{ runner.os }}-meson-build-

      - name: Build project
        run: |
          meson setup build
          meson compile -C build

      - name: Show binary info
        run: |
          file build/hw/vfb/Xvfb || true
          file build/hw/xfree86/Xorg || true

      - name: Upload Xvfb (if present)
        if: ${{ hashFiles('build/hw/vfb/Xvfb') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: Xvfb-arm64
          path: build/hw/vfb/Xvfb

      - name: Upload Xorg (if present)
        if: ${{ hashFiles('build/hw/xfree86/Xorg') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: Xorg-arm64
          path: build/hw/xfree86/Xorg